version: "3"

services:
  api:
    container_name: chat-api
    image: node:10-alpine
    volumes:
      - ./:/api
    working_dir: /api
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      MONGODB_URI: mongo/chat
    ports:
      - 3000:3000
    command: >
      sh -c "npm i && npm run dev"
  mongoclient:
    container_name: chat-dbvslzr
    image: mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - 8081:8081
  mongo:
    container_name: chat-db
    image: mongo
    expose:
      - 27017
    volumes:
      - ./tmp-mongo:/data/db
